### ISSUE TITLE
I can't download 

### ISSUE THREAD

**Issue by mscerutti** [githubteacher/fluffy-octo-guacamole#19]
How do I get help?

**Comment by halfaro1** [comment]
@mscerutti what in particular are you having trouble with? which step or which command? if you're not behind a company firewall, join us on [Gitter](https://gitter.im/githubteacher/fluffy-octo-guacamole?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) otherwise feel free to keep chatting here.

**Comment by halfaro1** [comment]
I'm closing this issue but feel free to reopen if you have a follow up or that still doesn't work 😄
